#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <fcntl.h>
#include <sys/wait.h>
#include <ctype.h>
#include "auxshell.h"

// author :  Santiago Rodriguez : rodriguez.santiago@correounivalles.edu.co
// date last mod: May 7, 2018.

 int main(int argc, char *argv[]){
 	while(1){
 		char command[80];
 		printf("~$");
 		scanf(" %[^\n]s", command); // se leen la lineas de la entrada.
 		if( ! strcmp(command, "exit")){
 			break;
 		}else{

 			int rc = fork();
				if (rc < 0) {// fork failed; exit
					fprintf(stderr, "fork failed\n");
					exit(1);
				} else if (rc == 0) { // child: redirect standard output to a file // not yet.
					char *myargs[40];
					discrimand(command, myargs);
					outToFile(myargs);
					if(existPipe(myargs)){
						piper(myargs);
						break;
					}else{
						execvp(myargs[0], myargs);  // runs command
						break;
					}
				//strcpy(command, "exit"); // failed try to fix exit trouble generated by non executed command.
				} else {// parent goes down this path (main)
					int wc = wait(NULL);
				}
			}
		}
		return 0;
	}

