#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <fcntl.h>
#include <sys/wait.h>
#include <ctype.h>
#include "auxshell.h"

// author :  Santiago Rodriguez : rodriguez.santiago@correounivalles.edu.co
// date last mod: May 7, 2018.

 int main(int argc, char *argv[]){
 	while(1){
 		char command[80];
 		printf("~$");
 		scanf(" %[^\n]s", command); // se leen la lineas de la entrada.
 		if( ! strcmp(command, "exit")){ // en caso de ser "exit", se sale del ciclo (break).
 			break;
 		}else{

 			int rc = fork();// creacion del hijo mediante el fork.
				if (rc < 0) {// fork failed; exit
					fprintf(stderr, "fork failed\n");// print error message.
					exit(1);//llamado a sistema.
				} else if (rc == 0) { // //el hijo ejecuta el comando.
					char *myargs[40];
					discrimand(command, myargs);// se separan las cadenas discriminadas por " " (espacios).
 					if(existPipe(myargs)){ // si existe un "|" (pipe).
						piper(myargs);// se ejecuta el piper que gestiona la ejecucion en pipe.
						break;// sale del ciclo del hijo despues de la ejecucion.
					}else{
						execvp(myargs[0], myargs);  // runs command
						break;//sale del ciclo del hijo luego de la ejecucion del comando.
					}
				//strcpy(command, "exit"); // failed try to fix exit trouble generated by non executed command.
				} else {// no queda mas que sea el padre en ese caso:
					int wc = wait(NULL);// el padre espera la terminacion de su hijos.
				}
			}
		}
		return 0;
	}

